version: '3'

services:
  app:
    image: kylemanna/openvpn
    restart: always
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
     - "53:53/tcp"
     - "53:53/udp"
    volumes:
     - config:/etc/openvpn

volumes:
  config:
